### ISSUE TITLE
Python files not being detected

### ISSUE THREAD

**Issue by smalbadger** [piotrpawlaczek/python-black-check#4]
Hello, I just tried this action for the first time and it says it can't find any python files. The repository I'm working on is [pymessagelib](https://github.com/smalbadger/pymessagelib). Here is what my directory structure looks like:

```
pymessagelib/
    | pymessagelib/
    |    | field.py
    |    | message.py
    | tests/
    |    | test_.......py
    ...
```

my main.yml file is:
```
  

name: Black-Lint

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: piotrpawlaczek/python-blacken@release/stable
        with:
          line-length: '120'
          path: '.'
```

I've played around with the path variable quite a bit but can't get it to work. Are you sure the current working directory is the root of the repo? I apologize if it's a dumb question - I'm just getting acquainted with GitHub actions.
